#!/bin/sh
. "$(dirname "$0")/_/husky.sh"

echo "🔍 Running tests before commit..."

npm run test:ci
RESULT=$?

if [ $RESULT -ne 0 ]; then
  echo "❌ Tests failed. commit aborted."
  exit 1
fi

echo "✅ All tests passed. Proceeding with commit."
exit 0